
import re

input_file = "파이썬으로_배우는_데이터분석입문9.md"
output_file = "파이썬으로_배우는_데이터분석입문9.md"

def main():
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()

    # 1. Refine Spacing in English Words
    # Common OCR issue: spaces inserted into words, e.g., "M atplotlib", "S eaborn"
    # This is a bit risky with regex, so we'll target specific known patterns from inspection.
    content = content.replace("M atplotlib", "Matplotlib")
    content = content.replace("S eaborn", "Seaborn")
    content = content.replace("D ataFrame", "DataFrame")
    content = content.replace("P ython", "Python")
    
    # 2. Fix specific broken strings found in Vol 9 text
    content = content.replace("s ns", "sns")
    content = content.replace("p lt", "plt")
    content = content.replace("H istogram", "Histogram")
    content = content.replace("S catter", "Scatter")
    content = content.replace("B ar", "Bar")
    content = content.replace("L ine", "Line")
    
    # 3. Code Block Cleanup (Safety Check)
    # Ensure ```python blocks don't have leading garbage on the same line
    content = re.sub(r"^`{3,}python\s+(.+)$", r"```python\n# \1", content, flags=re.MULTILINE)

    # 4. Remove any "Generated by..." or similar footer artifacts if they exist
    # (Manual check showed clean, but adding defensive removal)
    content = re.sub(r"Scanned by.*", "", content, flags=re.IGNORECASE)

    # 5. Fix potentially broken URLs
    content = content.replace("http ://", "http://")
    content = content.replace("https ://", "https://")

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(content)
        
    print(f"Refined {output_file} with Step 2 fixes.")

if __name__ == "__main__":
    main()
